### ISSUE TITLE
connection string changes

### ISSUE THREAD

**Issue by aprooks** [haf/EventStore.Client.FSharp#4]
There is an updated connection string syntax for 3.0.2. And current (with IPEndpoint) will be obsolete on next major release
 
>There are two new ways of creating a connection. 

>The first is to use a Uri. tcp://admin:changeit@mydomain:1113 as an 
>example. You can also use discover://admin:changeit@mydomain for 
>cluster discovery. A ConnectionSettings can also be passed with the 
>Uri. 

>The second is support for Connection Strings which can also set 
>settings. "Connect To=tcp://admin:changeit@localhost:1113;Heartbeat 
>Timeout = 5000;Max Retries = 5" as an example. `

https://groups.google.com/forum/#!topic/event-store/2Jj7_1qUlwE

**Comment by haf** [comment]
Thanks! That's good to know!

**Comment by haf** [comment]
I'm going to target the `EventStore.Client.PreRelease` until there's an official 3.1, because then there's less of a bump in the road when I suddenly have to update everything.
