### ISSUE TITLE
dev environment

### ISSUE THREAD

**Issue by aprooks** [haf/EventStore.Client.FSharp#5]
Hi, I'm having some issues with VS2013: lot's of warnings and had to add FSharp.Core redirect like this one http://blog.ploeh.dk/2014/01/30/how-to-use-fsharpcore-430-when-all-you-have-is-431/

So what are you using, VS 2012 or Mono stuff?

**Comment by haf** [comment]
Yes, mono, which is more lenient and doesn't crash on this particular issue.

Here's the reference: https://github.com/haf/EventStore.Client.FSharp/blob/master/src/EventStore.ClientAPI.FSharp/EventStore.ClientAPI.FSharp.fsproj#L61

It's for the very latest F#, as you can see.

We had to add app.config to support Windows in Suave, too, so if you send a PR I'll merge ;)

**Comment by aprooks** [comment]
Ok, I'll check how it is done in Suave first

**Comment by haf** [comment]
It's the way you did it.

**Comment by aprooks** [comment]
Just wanted to be Sure. Uploaded PR: #6 . Didn't setup Mono environment, and didn't test it as well.
