### ISSUE TITLE
testing against Embedded server

### ISSUE THREAD

**Issue by aprooks** [haf/EventStore.Client.FSharp#7]
I've had an error `EventStore.ClientAPI.Exceptions.ServerErrorException: Unexpected error on server: Couldn't unwrap network package for command {commandName}` while testing against embedded store. 

I have found that they are not using TcpConnection, but use node queues directly
https://github.com/EventStore/EventStore/blob/8b64afa658a054407ebe5e6d92a7a0ec0ffceba2/src/EventStore.ClientAPI.Embedded/EmbeddedEventStoreConnection.cs

So this snippets creates a working connection
```FSharp
let node = 
    EmbeddedVNodeBuilder
        .AsSingleNode()
        .OnDefaultEndpoints()
        .RunInMemory()
        .RunProjections(ProjectionsMode.All)
        .WithWorkerThreads(16).Build()
node.Start()

let embeddedConn = 
     let emb = EmbeddedEventStoreConnection.Create (node)
     emb.ApiWrap()
```

Though if appending was working via TcpConnection under mono, it could be another windows bug

**Comment by haf** [comment]
The EmbeddedVNode code is buggy in how it starts and stops: https://github.com/EventStore/EventStore/issues/322 - which has been fixed a good while ago, but because of a large effort required for releases, hasn't be officially released (not even as a pre-release nuget).

Right now the tests are pretty flaky for this reason. I suggest you forward this error message to EventStore proper. I can run all tests (that aren't commented out, or ignored) on mono.

**Comment by aprooks** [comment]
Thank you. I'll wait for 3.0.2 and review this issues again.

**Comment by haf** [comment]
So they haven't yet merged that, but since I'm switching this lib over to EventStore.Client.PreRelease which I have control over, I can fix the bug.

Can I let you know when it's possible to test again?

**Comment by haf** [comment]
I've merged now! Could you test?

**Comment by aprooks** [comment]
Hi, I will tonight or tomorrow. Thank you for update

**Comment by aprooks** [comment]
I could not run it at all:(

```
Exception: System.TypeInitializationException: Инициализатор типа "EventStore.Core.Bus.InMemoryBus" выдал исключение. ---> System.TypeInitializationException: Инициализатор типа "EventStore.Common.Log.LogManager" выдал исключение. ---> System.IO.FileLoadException: Не удалось загрузить файл или сборку "NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c" либо одну из их зависимостей. Найденное определение манифеста сборки не соответствует ссылке на сборку. (Исключение из HRESULT: 0x80131040)
   в EventStore.Common.Log.LogManager..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в EventStore.Common.Log.LogManager.GetLoggerFor[T]()
   в EventStore.Core.Bus.InMemoryBus..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в EventStore.Core.Bus.InMemoryBus..ctor(String name, Boolean watchSlowMsg, Nullable`1 slowMsgThreshold)
   в EventStore.Core.ClusterVNode..ctor(TFChunkDb db, ClusterVNodeSettings vNodeSettings, IGossipSeedSource gossipSeedSource, InfoController infoController, ISubsystem[] subsystems)
   в EventStore.ClientAPI.Embedded.EmbeddedVNodeBuilder.Build()
```

I did try to reference NLog of 2.0.0.2000 (it's the ealiest possible), but it didn't help

This is a test I've added to get this error.
```
(* projectionsTests.fs*)

    testCase "write event" <| fun _ ->
        withConnection eventStoreImpl <| fun conn ->
            let evData = EventData.Empty
            
            conn.AppendToStream ("test",ExpectedVersionUnion.Any,proj_ctx.creds,[unwrapEventData evData])
            |> Async.AwaitTask
            |> Async.RunSynchronously
            |> ignore
```

**Comment by haf** [comment]
The problem with EventStore is that they don't supply pre-release binaries and I haven't had time to fiddle with the project enough to ILMerge NLog and protobuf-net properly. Thanks for the report, I'll let you know on progress.
